/* Auto-generated from duckdb_errors.txt — do not edit. */
#pragma once

#define ER_DUCKDB_CLIENT 4257
#define ER_DUCKDB_QUERY_ERROR 4258
#define ER_DUCKDB_TABLE_STRUCT_INVALID 4259
#define ER_DUCKDB_SEND_RESULT_ERROR 4260
#define ER_DUCKDB_APPENDER_ERROR 4261
#define ER_DUCKDB_COMMIT_ERROR 4262
#define ER_DUCKDB_ROLLBACK_ERROR 4263
#define ER_DUCKDB_PREPARE_ERROR 4264
